global:
  container:
    requestsLimitsEnabled: true
  istio:
    sidecar:
      requestsLimitsEnabled: true
      resources:
        requests: {}
        limits: {}
  kafkaOperator:
    replicationFactor: 3
  registry:
    userSettingsServiceApi:
      container:
        envVars: {}
        resources:
          requests: {}
          limits: {}
      hpa:
        enabled: false
        minReplicas: 1
        maxReplicas: 3
      istio:
        sidecar:
          enabled: true
          resources:
            requests: {}
            limits: {}
      replicas: 1

name: user-settings-service-api

version: 1.1.0

deployProfile: prod

port: 8080

service:
  port: 8080

ingress:
  required: true
  site: settings-api

kafka:
  service: kafka-cluster-kafka-bootstrap:9093
  user: settings-api-user
  clusterName: kafka-cluster
  sslEnabled: true
  sslCertType: PEM
  sslUserKey: ${KAFKA_USER_KEYSTORE_KEY}
  sslUserCertificate: ${KAFKA_USER_KEYSTORE_CERTIFICATE}
  sslClusterCertificate: ${KAFKA_CLUSTER_TRUSTSTORE}

image:
  name: user-settings-service-api
  version: latest

monitoring:
  namespace: openshift-monitoring
  prometheusScrapePath: /actuator/prometheus
  jobLabel: app

probes:
  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness

audit:
  kafka:
    topic: audit-events
    schemaRegistryUrl: http://kafka-schema-registry:8081

keycloak:
  realms:
    officer: officer-portal
    citizen: citizen-portal
    admin: admin
  certificatesEndpoint: /protocol/openid-connect/certs

db:
  url: citus-master
  secret: citus-roles-secrets
  name: settings
  port: 5432
  connectionTimeout: 4000

redis:
  secretName: redis-auth

redisSecretsMountPath: "/app/secrets/redis"

verification:
  otp:
    timeToLive: 300
