{{- if or (not .Values.global.excludePortals) (not (has "citizen" .Values.global.excludePortals)) (not (has "officer" .Values.global.excludePortals)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
{{- end }}